export const API_ENDPOINTS = {

    CustGetLogin : 'CustGetLogin',
    CustLoginWithMobile : 'CustLoginWithMobile', 
    CustVerifyOTP : 'CustVerifyOTP',
    CustSaveSignup : 'CustSaveSignup',
    CustForgotpassword : 'CustForgotpassword',
    GetCustomerKycStatus: 'GetCustomerKycStatus',
    GetHeaderSymbols : 'GetHeaderSymbols',
    getTopGainer : 'getTopGainer',
    getTopLooser : 'getTopLooser',
    getoptionlistPE : 'getoptionlistPE',
    getoptionlistCE : 'getoptionlistCE',
    GetWatchListByUserId : 'GetWatchListByUserId',
    getoptionexpiryList : 'getoptionexpiryList',
    CustGetProfile: 'CustGetProfile', // Add this line
    GetCustBrokerConfig : 'GetCustBrokerConfig',
    GetBokerMaster : 'GetBokerMaster',
    GetCustBrokerConfigByID : 'GetCustBrokerConfigByID',
    getRecordsHistoricalList : 'getRecordsHistoricalList',
    PostCustBrokerConfig : 'PostCustBrokerConfig',
    ChoiceBrokerLogin : 'ChoiceBrokerLogin',
    VerifyKotakUserOtp : 'VerifyKotakUserOtp',
    PostCustBrokerStatus : 'PostCustBrokerStatus',
    getLotsizeBysymbol : 'getLotsizeBysymbol',
    PostCreateOrder : 'PostCreateOrder',
    PostUpdateOrder : 'PostUpdateOrder',
    GetOrderListActive : 'GetOrderListActive',
    GetOrderListClosed : 'GetOrderListClosed',
    GetOrderListRejected : 'GetOrderListRejected',
    GetOrderListPending : 'GetOrderListPending',
    GetdayorderProfitLoss : 'GetdayorderProfitLoss',
    GetSymbolcat : 'GetSymbolcat',
    GetSymbolcatAll : 'GetSymbolcatAll',
    RoundoffOrders : 'RoundoffOrders',
    SymbolIdentifierByCustomerID : 'SymbolIdentifierByCustomerID',
    GetSymbolCatogeryList : 'GetSymbolCatogeryList',
    GetCustomerOptionsAlgo : 'GetCustomerOptionsAlgo',
    AutoTradeAllowed : 'AutoTradeAllowed',
    PostCustomerOptionsLegAlgo : 'PostCustomerOptionsLegAlgo',
    PostCustomerAlgoTrade : 'PostCustomerAlgoTrade',
    getStratergyList : 'getStratergyList',
    GetAllOrderList : 'GetAllOrderList',
   
    GetPlatforms : 'GetPlatforms',
    GetCustomerAlgoTradeByID : 'GetCustomerAlgoTradeByID',
    AddWatchList : 'AddWatchList',
    GetCustomerSubscription : 'GetCustomerSubscription',
    GetSubscriptionExpiry : 'GetSubscriptionExpiry',
    GetCustomerApiKey : 'GetCustomerApiKey',
    GetSymbolIdentifierByCategory : 'GetSymbolIdentifierByCategory',
    GetSignalFormat : 'GetSignalFormat',
    GenerateApiKey : 'GenerateApiKey',
    PostCustomerAlgoTradeStatus : 'PostCustomerAlgoTradeStatus',
    PostCustomerOptionsAlgoStatus : 'PostCustomerOptionsAlgoStatus',
    GetUnreadNotificationByCustomerID : 'GetUnreadNotificationByCustomerID',
    GetNotificationByCustomerID : 'GetNotificationByCustomerID',
    PostNotificationStatus : 'PostNotificationStatus',
    PostTrendStrategyData : 'TrendStrategy/PostTrendStrategyData',
    PostScalping:'Scalping/PostScalpingData',
    GenerateConsent: 'GenerateConsent',
    ConsumeConsent: 'ConsumeConsent',
    GetBrokerAvailableCash:"GetBrokerAvailableCash"
}


export const NODE_API_ENDPOINTS = {
    addAlgo : 'algo/add',
    getAlgo : 'algo/get',
    startBacktest : 'back_testing',
    startStrategyBacktest : 'back_testing/strategy',
    helpCategories : 'help/categories',
    supportCategories : 'support/categories',
    createSupportTicket : 'support/tickets',
    getUserTickets : 'support/tickets',
    helpStructure : 'help/structure',
    strategyDescription : 'strategy',
    getNewsList : 'news/list',
    getNewsDetail : 'news/detail',
    getVideosList : 'videos',
    getVideoById : 'videos',
    searchVideos : 'videos/search',
    getVideosByCategory : 'videos/category',
    getDashboardData : 'dashboard',
    getAdminStrategy : 'api/strategy/list/admin',
    getClientStrategy : 'api/strategy/list/client',
    getActiveStrategies : 'api/strategy/active',
    getStrategyDetails : 'api/strategy/details',
    getAdminStrategyDetails : 'api/strategy/admin-details',
    getStrategyOrders : 'api/strategy/orders',
    deployAdminStrategy : 'api/strategy/deploy',
    updateStrategyBroker : 'api/strategy/broker/update',
    stopStrategy : 'api/strategy/stop'
}